In [1]:
ages=[19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.sort()  #for sorting
print(ages)

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]


In [2]:
print(max(ages)) #returns max age


26


In [3]:
print(min(ages)) #returns min age

19


In [4]:
ages.append(min(ages))#adds min age to the list
ages.append(max(ages))#adds max age to the list
print(ages)

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]


In [8]:
ages.sort()
if len(ages)%2!=0:
    median=int((len(ages)+1)/2-1)
    print(median)
else:
    median1=int(len(ages)/2-1)
    median2=int(len(ages)/2)
    print((ages[median1]+ages[median2])/2)

24.0


In [10]:
Average_Age=sum(ages)/len(ages)  #for average age
print(Average_Age)

22.75


In [11]:
Range=max(ages)-min(ages)  #range
print(Range)

7


In [12]:
#2
dog={} #creates empty dictionary 
dog={'name':'cashew','breed':'golden retriever','color':'golden','legs':'4','age':'2'}
print(dog)

{'name': 'cashew', 'breed': 'golden retriever', 'color': 'golden', 'legs': '4', 'age': '2'}


In [13]:
student={'first_name':'yami','last_name':'macherla','gender':'female','marital status':'single','skills':['c','java','python'],'country':'India','city':'nizambad','address':'ankapur'}
print(len(student)) #returns length of student dictionary 


8


In [14]:
print(student['skills']) #returns skills from student 
print(type(student['skills'])) #returns type of skills


['c', 'java', 'python']
<class 'list'>


In [15]:
print(list(student.keys()))#returns keys of student
print(list(student.values()))#returns values of student

['first_name', 'last_name', 'gender', 'marital status', 'skills', 'country', 'city', 'address']
['yami', 'macherla', 'female', 'single', ['c', 'java', 'python'], 'India', 'nizambad', 'ankapur']


In [18]:
#3
brothers=('yash','madhu') #creates tuple 
sisters=('manu','mammu')
siblings=brothers+sisters #joins tuples brothers and sisters
#as tuple is immutable ,we cannot modify values in a tuple
print(len(siblings)) 
family_members=siblings+('gangareddy','latha')
print(family_members)

4
('yash', 'madhu', 'manu', 'mammu', 'gangareddy', 'latha')


In [20]:
#4
it_companies={'Facebook ','Google','Microsoft','Apple','IBM','Oracle','Amazon'}
print(len(it_companies))
it_companies.add('Twitter')
print(it_companies)
it_companies.update(['TCS','Wipro','HCL']) # inserts multiple companies to set it_companies
it_companies.remove('HCL')# removes hcl
print(it_companies)

# The difference between the two functions is that discard() function leaves a set unchanged if the element is not present in set. On the other hand, the remove() function will raise an error in such a condition (if element is not present in the set).

A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
print(A.union(B)) #joins A&B
print(A.intersection(B)) # returns elements present in both sets 
print(A.issubset(B))# returns true or false
print(A.isdisjoint(B))
C = A.union(B)#joins a with b and stores in c
print(C)
D = B.union(A)#joins b with a and stores in D
print(D)
print(A.symmetric_difference(B))
A.clear()#deletes the set 
B.clear()

age = [22, 19, 24, 25, 26, 24, 25, 24]
age_set = set(age)#converts age to the set
print(len(age))#length of list
print(len(age_set))#  returns length of set


7
{'IBM', 'Google', 'Twitter', 'Microsoft', 'Oracle', 'Amazon', 'Apple', 'Facebook '}
{'Twitter', 'Facebook ', 'Apple', 'Oracle', 'TCS', 'IBM', 'Microsoft', 'Amazon', 'Wipro', 'Google'}
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}
{27, 28}
8
5


In [22]:
##5
radius= input('Radius =')
_area_of_circle_ = (3.14) * (int(radius)**2)
print('Area of circle is',_area_of_circle_)
_circum_of_circle_ = 2 * (3.14) * int(radius)
print('Circumference of circle is',_circum_of_circle_)

Radius =30
Area of circle is 2826.0
Circumference of circle is 188.4


In [23]:
#6
string = 'I am a teacher and I love to inspire and teach people'
list = string.split(' ') # splits the string and converts in to list
set=set(list) #converts list into set 
unique_words=0
for i in set:
    count=0
    for j in range(len(list)):  #comparing the set elements with list elements recursively
        if(i==list[j]): 
            count+=1
    if(count==1):  # to find the count
        unique_words+=1
    count=1
print(unique_words)

8


In [24]:
#7
print('Name\t\tage\t\tcountry\t\tcity\n''Asabeneh\t250\t\tFinland\t\tHelsinki')

Name		age		country		city
Asabeneh	250		Finland		Helsinki


In [25]:
#8
radius = 10
area =  3.14 * radius ** 2 #area of circle

print('The area of a circle with radius 10 is {} meters square'.format(int(area)))

The area of a circle with radius 10 is 314 meters square


In [1]:
#9
N=int(input('Enter the Number of Students:'))
Weight_lst_lbs=[]
Weight_lst_kgs=[]
#This program uses the below formula
#1lb = 0.453592 kg
for i in range(1, N+1): 
      Weight= int(input('Enter Student{} weight:'.format(i))) 
      Weight_lst_lbs.append(Weight)
#Converting lbs list to kgs list
for i in range(0,N):
       W=Weight_lst_lbs[i]*0.453592
       Weight_lst_kgs.append(round(W,2))
#Printing wieght list in kgs
print(Weight_lst_kgs)

Enter the Number of Students:5
Enter Student1 weight:56
Enter Student2 weight:23
Enter Student3 weight:89
Enter Student4 weight:95
Enter Student5 weight:98
[25.4, 10.43, 40.37, 43.09, 44.45]


In [2]:
#Question 10
import numpy as nm   
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import confusion_matrix 

X= nm.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
print("Dataset with total 8 points: \n",X,"\n Size: ",len(X))
y = nm.array([0,0,1,1,1,0,0,0])
print("\nClass label for the datasetX  Y:",y)
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.50, random_state=0,shuffle=False ) 
print("\nTraining Data X: \n", x_train)
print("\nTraining Data label Y:", y_train)

#feature Scaling-used to normalize the range of independent variables or features of data. .
#i.e.to standardize the data prior to performing classification 
stand_scalar= StandardScaler()    
x_train= stand_scalar.fit_transform(x_train)    
x_test= stand_scalar.transform(x_test) 

#Initialising KNN Classifier with value 3
classifier= KNeighborsClassifier(n_neighbors=3)  
#Fitting the data to classifier
classifier.fit(x_train, y_train)
#Predict Labels for x-test data
y_pred= classifier.predict(x_test) 
print('\nPredicted Classs labels for testing data Y:',y_pred)
     
#Confusion matrix with tested data
confusion_matrix_result = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix\n",confusion_matrix_result)

#total P+N can be calculated using sum(sum(conf_matrix))
total_value = sum(sum(confusion_matrix_result))
#Accuracy TN+TP / P+N
accuracy=(confusion_matrix_result[0,0]+confusion_matrix_result[1,1])/total_value
print ('\nAccuracy : ', accuracy)

#Sensitivity TP/(TP+FN)
sensitivity = confusion_matrix_result[1,1]/(confusion_matrix_result[1,0]+confusion_matrix_result[1,1])
print('Sensitivity : ', sensitivity )

#Specificity TN/(TN+FP)
specificity = confusion_matrix_result[0,0]/(confusion_matrix_result[0,0]+confusion_matrix_result[0,1])
print('Specificity : ', specificity)


Dataset with total 8 points: 
 [[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 6  0]
 [ 6  0]
 [ 7  0]
 [10  0]
 [11  0]] 
 Size:  8

Class label for the datasetX  Y: [0 0 1 1 1 0 0 0]

Training Data X: 
 [[1 0]
 [2 0]
 [3 0]
 [6 0]]

Training Data label Y: [0 0 1 1]

Predicted Classs labels for testing data Y: [1 1 1 1]

Confusion Matrix
 [[0 3]
 [0 1]]

Accuracy :  0.25
Sensitivity :  1.0
Specificity :  0.0
